[project]
name = "lightweight-search-graph"
authors = ["Open Source Community"]
description = "A decentralized graph-based search protocol built on Stacks"
telemetry = false
requirements = []
[contracts.graph-index]
path = "contracts/graph-index.clar"
depends_on = []

[contracts.graph-resolver]
path = "contracts/graph-resolver.clar"
depends_on = []

[contracts.graph-access-control]
path = "contracts/graph-access-control.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
